version: "3.9"

services:
  db:
    image: postgres:14.9
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - milk-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  milk-db-data: {}
